---
exclude: |
  (?x)
  ^README\.md$|
  # Repos using Sphinx to generate docs don't need prettying
  ^docs/_templates/.*\.html$|
  # You don't usually want a bot to modify your legal texts
  (LICENSE.*|COPYING.*)
ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
default_stages: [commit]
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
        args: ["--no-cache"]
      - id: poetry-lock
        args: ["--no-cache"]
      - id: poetry-export
        name: Export requirements.txt
        args:
          [
            "--no-cache",
            "--without-hashes",
            "--without",
            "dev",
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
          ]
      - id: poetry-export
        name: Export requirements-dev.txt
        args:
          [
            "--no-cache",
            "--without-hashes",
            "--with",
            "dev",
            "-f",
            "requirements.txt",
            "-o",
            "requirements-dev.txt",
          ]
      - id: poetry-export
        name: Export requirements-test.txt
        args:
          [
            "--no-cache",
            "--without-hashes",
            "--with",
            "test",
            "-f",
            "requirements.txt",
            "-o",
            "requirements-test.txt",
          ]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier"
          - "prettier-plugin-toml"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          ["--ignore-missing-imports", "--python-version=3.8"]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        args: ["--py36-plus"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--fix", "--config=pyproject.toml"]
      - id: ruff-format
        args: ["--config=pyproject.toml"]
