name: Develop

on:
  push:
    branches:
      - dev
      - develop
    paths:
      - "**/*.py"
      - ".github/workflows/develop.yml"
  pull_request:
    branches:
      - dev
      - develop
    paths:
      - "**/*.py"
      - ".github/workflows/develop.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make deps

      - name: Run tests
        run: |
          make test
