name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "**/*.py"
      - ".github/workflows/release.yml"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Katulos'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
